In [1]:
import torch
import torch.nn as nn

In [ ]:
prediction= torch.randn(4,5)
prediction

In [11]:
label = torch.randn(4,5)
label

tensor([[-0.5610,  1.2852, -1.0073,  0.1685, -1.9928],
        [ 0.2057,  0.2684, -1.0869,  1.1856,  1.2634],
        [ 0.4809, -0.7465,  0.6741, -0.9712,  0.4907],
        [ 0.3819,  1.5167,  2.6458, -1.0892, -0.3596]])

In [12]:
mse= nn.MSELoss(reduction='none') # none doestn do any reduction
mse

MSELoss()

In [9]:
loss=mse(prediction,label)
print(loss)

tensor([[2.5735e+00, 4.1438e+00, 6.2454e+00, 5.0853e-01, 1.7167e-01],
        [2.6358e-01, 2.0091e+00, 9.1742e-01, 4.1105e-01, 2.4862e-01],
        [3.2571e+00, 4.1572e-01, 1.5332e+00, 1.1066e-02, 1.2666e+01],
        [3.9428e+00, 2.7889e-04, 3.3208e+00, 2.9862e-03, 1.9605e+00]])


In [13]:
mse= nn.MSELoss(reduction='mean') # mean -- is a mean of all tensor
mse

MSELoss()

In [14]:
loss=mse(prediction,label)
print(loss)

tensor(3.2526)


In [15]:
mse= nn.MSELoss(reduction='mean') # sum -- summ all in tensor
loss=mse(prediction,label)
print(loss)

tensor(3.2526)


In [17]:
((prediction-label)**2).mean()

tensor(3.2526)

In [18]:
label = torch.zeros(4,5).random_(0,2)
label

tensor([[0., 0., 0., 1., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 0., 0., 1.],
        [0., 0., 1., 1., 1.]])

In [19]:
sigmoid = nn.Sigmoid()
bce=nn.BCELoss(reduction='mean')
bce(sigmoid(prediction),label)

tensor(0.8512)

In [20]:
bces=bce=nn.BCEWithLogitsLoss(reduction='mean')

In [21]:
bce(prediction,label)

tensor(0.8512)

In [41]:
import numpy as np
x=prediction.numpy()
y=label.numpy()


In [23]:
loss_values=[]
for i in range(len(label(y))):
    batch_loss=[]
    for j in range(len(y[0])):
        if y[i][j]== 1:
            loss= -np.log(x[i][j])
        else:
            loss= -np.log(1-x[i][j])
            
        batch_loss.append(loss)
    loss_values.append(batch_loss)

SyntaxError: incomplete input (2743265576.py, line 4)

In [33]:
def sigmoid(x):
    return 1/(1+ np.exp(-x))

In [42]:
#optimized
x= sigmoid(x)
loss_values=[]
for i in range(len(y)):
    batch_loss=[]
    for j in range(len(y[0])):
        batch_loss.append(-np.log(x[i][j]) if y[i][j]== 1 else -np.log(1-x[i][j]))

    loss_values.append(batch_loss)
print(np.mean(loss_values))

0.8512226068344585


In [ ]:
# if we encounter nan value that means we forgot to do sigmoid activation func