In [1]:
import torch

In [2]:
a=torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
b=torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
c=torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(c)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])


In [6]:
d=torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(d)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)


In [7]:
print(c.mean())

tensor(2.5833)


In [8]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [9]:
print(c.std())

tensor(1.5050)


In [10]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [12]:
# Reshape b
#Note: if one of the dimentions is -1 its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b=b.view(1,-1)
print(b)
print(b.shape)
#we can even reshape 3d tensors
print('\n')
#Create a 3d Tensor with 2 channels,3 rows,and 4 columns 
three_dim=torch.randn(2,3,4)
print('\n')
print(three_dim)
print(three_dim.view(2,12))
print(three_dim.view(2,-1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[-0.3801, -0.5721,  0.7882,  0.1223],
         [ 1.3892,  0.1558, -0.2304, -0.3893],
         [ 1.5075,  0.7649, -0.3983,  0.5905]],

        [[ 0.9012, -0.3783,  1.1543, -0.8194],
         [ 1.3427,  1.4874,  0.6196, -2.2705],
         [-0.1457, -0.2628, -2.0472, -0.5368]]])
tensor([[-0.3801, -0.5721,  0.7882,  0.1223,  1.3892,  0.1558, -0.2304, -0.3893,
          1.5075,  0.7649, -0.3983,  0.5905],
        [ 0.9012, -0.3783,  1.1543, -0.8194,  1.3427,  1.4874,  0.6196, -2.2705,
         -0.1457, -0.2628, -2.0472, -0.5368]])
tensor([[-0.3801, -0.5721,  0.7882,  0.1223,  1.3892

In [13]:
#Create a matrix with random numbers betwoon 0 and 1
r=torch.rand(4,4)
print(r)

tensor([[0.0152, 0.6753, 0.3068, 0.9674],
        [0.9687, 0.7579, 0.5182, 0.6318],
        [0.2081, 0.0592, 0.5473, 0.5452],
        [0.6891, 0.3897, 0.8718, 0.9356]])


In [14]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2=torch.rand(4,4)
print(r2)
print(r2.type)

tensor([[0.1201, 0.1442, 0.6448, 0.8497],
        [0.8339, 0.1152, 0.5614, 0.3465],
        [0.1192, 0.1165, 0.3698, 0.8054],
        [0.4384, 0.2038, 0.2756, 0.6921]])
<built-in method type of Tensor object at 0x000001EAEAE9CCC0>


In [15]:
#create an array of 5 random integers from values between 6 and 9 (exclusive of 10)
in_array= torch.randint(6,10,(5,))
print(in_array)
print(in_array.dtype)

tensor([9, 6, 7, 8, 9])
torch.int64


In [16]:
# Create a 2-d array (of matrix) of size 3x3 filled with random integers from values betwoon 6 and 9 (exclosive of 10)
in_array2=torch.randint(6,10,(3,3))
print(in_array2)

tensor([[7, 9, 6],
        [9, 7, 8],
        [6, 7, 6]])


In [17]:
#get the number of elements in in_array
print(torch.numel(in_array))
#get the number of elemnts in in_array2
print(torch.numel(in_array2))

5
9


In [18]:
#Construc a 3x3 matrix of zeroes and of dtype Long:
z=torch.zeros(3,3,dtype=torch.long)
print(z)
#construct a 3x3 matrix of ones
o= torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [19]:
r2_like=torch.randn_like(r2,dtype=torch.double)
print(r2_like)

tensor([[-0.0267,  1.3016,  0.6365,  0.5622],
        [ 0.8673, -0.4803,  0.1147, -1.2867],
        [-0.8712, -0.6863, -0.6766, -1.5945],
        [ 0.8821,  0.3625, -1.1661, -1.1103]], dtype=torch.float64)


In [20]:
#add two tensors, maeke sure they are the same size and data type
add_result=torch.add(r,r2)
print(add_result)

tensor([[0.1353, 0.8195, 0.9516, 1.8170],
        [1.8025, 0.8732, 1.0796, 0.9783],
        [0.3272, 0.1758, 0.9171, 1.3506],
        [1.1275, 0.5934, 1.1473, 1.6277]])


In [21]:
# in place additionn (change the value of r2)
r2.add(r)
print(r2)

tensor([[0.1201, 0.1442, 0.6448, 0.8497],
        [0.8339, 0.1152, 0.5614, 0.3465],
        [0.1192, 0.1165, 0.3698, 0.8054],
        [0.4384, 0.2038, 0.2756, 0.6921]])


In [22]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten=r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([0.1442, 0.1152, 0.1165, 0.2038])
tensor([[0.1201, 0.1442],
        [0.8339, 0.1152],
        [0.1192, 0.1165],
        [0.4384, 0.2038]])
tensor([[0.1201, 0.1442, 0.6448, 0.8497],
        [0.8339, 0.1152, 0.5614, 0.3465],
        [0.1192, 0.1165, 0.3698, 0.8054]])
tensor(0.8054)
0.8054125905036926
tensor([0.1192, 0.1165, 0.3698, 0.8054])


# Numpy Bridge

In [23]:
import numpy as np

In [24]:
#Converting a Torch tensor to a Numpy array
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
#see how the numpy array changed their value
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
#Converting Numpy array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
#Move the tensor to the GPU
r2=r2.cuda()
print(r2)

AssertionError: Torch not compiled with CUDA enabled

In [27]:
#provide easy switching between CPU and GPU
CUDA=torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result=add_result.cuda()
    print(add_result)

False


In [28]:
data=[[1.,2.],[3,4.],[5.,6.],[7.,8.]]
T=torch.tensor(data)
print(T,T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


In [31]:
#Tensor Concatenation
first_1 = torch.randn(2,5)
print(first_1)
second_1=torch.randn(3,5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1=torch.cat([first_1,second_1])
print('\n')
print(con_1)
print('\n')
first_2=torch.randn(2,3)
print(first_2)
second_2=torch.randn(2,5)
print(second_2)
#Concatenate along the 1 dimension (concatenate columns)
con_2=torch.cat([first_2,second_2],1)
print('\n')
print(con_2)
print('\n')

tensor([[-0.3690,  0.9795, -0.7149,  0.1343, -1.4367],
        [-0.7619,  0.2167,  0.7678, -0.2433, -0.9056]])
tensor([[-0.7192, -0.6598, -0.3239,  0.6584,  1.2669],
        [-0.2534,  1.1116, -0.0374, -1.5747,  0.3073],
        [-0.3332,  0.8844,  0.0758,  1.6789, -0.8085]])


tensor([[-0.3690,  0.9795, -0.7149,  0.1343, -1.4367],
        [-0.7619,  0.2167,  0.7678, -0.2433, -0.9056],
        [-0.7192, -0.6598, -0.3239,  0.6584,  1.2669],
        [-0.2534,  1.1116, -0.0374, -1.5747,  0.3073],
        [-0.3332,  0.8844,  0.0758,  1.6789, -0.8085]])


tensor([[-1.1714,  0.1896,  1.1623],
        [ 0.2524,  1.3178, -0.7994]])
tensor([[-0.3486, -2.3121,  0.4427, -0.0500, -0.4535],
        [ 1.3297,  0.2050, -1.3135, -1.1241, -0.4722]])


tensor([[-1.1714,  0.1896,  1.1623, -0.3486, -2.3121,  0.4427, -0.0500, -0.4535],
        [ 0.2524,  1.3178, -0.7994,  1.3297,  0.2050, -1.3135, -1.1241, -0.4722]])




# Adding Dimensions to Tensors

In [34]:
tensor_1=torch.tensor([1,2,3,4])
tensor_a=torch.unsqueeze(tensor_1,0)
print(tensor_a)
print(tensor_a.shape)
tensor_b=torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2=torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c=tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d=torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.9507, 0.8474, 0.0456, 0.2727],
         [0.9399, 0.6040, 0.9175, 0.1754],
         [0.5283, 0.6604, 0.3022, 0.6991]],

        [[0.6199, 0.8866, 0.8614, 0.8308],
         [0.6554, 0.4696, 0.2574, 0.3148],
         [0.5125, 0.2214, 0.1298, 0.1707]]])


tensor([[0.0456, 0.9175, 0.3022],
        [0.8614, 0.2574, 0.1298]])
torch.Size([2, 3])


tensor([[[0.0456],
         [0.9175],
         [0.3022]],

        [[0.8614],
         [0.2574],
         [0.1298]]])
torch.Size([2, 3, 1])


# AutoGrad (automaic differentiation)

In [35]:
# If requires_grad=True,the Tensor object keeps track of how it was created.
x=torch.tensor([1.,2.,3],requires_grad=True)
y=torch.tensor([4.,5.,6],requires_grad=True)
#Both x and y have their requirede_grad se to true, therefore we can compute gradients with respect to them
z=x+y
print(z)
# z knows that it was create as a result of addition of x and y. it knows that it wasnt read in from a file
print(z.grad_fn)
# And we go further on this
s=z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [36]:
# Now if we backpropogate on s, we can find gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [37]:
#By default, Tensors have `requres_grad=False`
x=torch.randn(2,2)
y=torch.randn(2,2)
print(x.requires_grad,y.requires_grad)
z=x+y
#so you cant backprop through z
print(z.grad_fn)
#Another way to set the requires_grad=True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients,as we saw above
z=x+y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z=z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``,but with the computation history forgotten.
# it doesnt know anyting about how it was computed in other wordsm we have broken the Tensor away from its past history

# You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [38]:
x= torch.ones(2,2,requires_grad=True)
print(x)
y=x+2
print(y)
print(y.grad_fn)
z=y*y*3
out=z.mean()
print(z,out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
#Loss functions!!!