In [2]:
import torch
import torch.nn.functional as F

In [3]:
predictions= torch.log(torch.rand(3))

In [5]:
predictions

tensor([-1.3188, -3.6103, -0.0423])

In [8]:
print(F.softmax(predictions,dim=-1))
print(F.softmax(predictions/0.5,dim=-1))
print(F.softmax(predictions/0.1,dim=-1))

tensor([0.2134, 0.0216, 0.7650])
tensor([7.2178e-02, 7.3792e-04, 9.2708e-01])
tensor([2.8604e-06, 3.1948e-16, 1.0000e+00])


In [7]:
print(F.softmax(predictions,dim=-1))
print(F.softmax(predictions/5,dim=-1))
print(F.softmax(predictions/100,dim=-1))

tensor([0.2134, 0.0216, 0.7650])
tensor([0.3421, 0.2163, 0.4416])
tensor([0.3344, 0.3269, 0.3387])
