In [1]:
import torch
import torch.nn as nn

In [5]:
layer = nn.Linear(5,5)
layer.weight

Parameter containing:
tensor([[ 0.4177, -0.1009,  0.2661, -0.2513, -0.2045],
        [-0.1212, -0.3192, -0.2318, -0.3838,  0.2761],
        [ 0.2042, -0.3384,  0.0663,  0.2968,  0.0430],
        [ 0.3513,  0.1752, -0.0406, -0.4325, -0.4222],
        [-0.1658,  0.0721,  0.1407, -0.0065, -0.3227]], requires_grad=True)

In [6]:
layer.weight.data

tensor([[ 0.4177, -0.1009,  0.2661, -0.2513, -0.2045],
        [-0.1212, -0.3192, -0.2318, -0.3838,  0.2761],
        [ 0.2042, -0.3384,  0.0663,  0.2968,  0.0430],
        [ 0.3513,  0.1752, -0.0406, -0.4325, -0.4222],
        [-0.1658,  0.0721,  0.1407, -0.0065, -0.3227]])

In [8]:
nn.init.uniform_(layer.weight.data,a=0.0,b=3)

tensor([[1.9552, 1.0154, 2.7024, 0.0830, 1.2568],
        [2.6414, 2.5320, 0.3748, 1.4786, 1.2738],
        [1.9181, 0.5866, 2.5842, 1.5479, 0.7514],
        [2.9184, 2.6073, 0.6325, 2.2368, 0.4774],
        [1.5555, 2.8263, 0.3460, 2.8369, 2.3498]])

In [9]:
nn.init.normal_(layer.weight,mean=0.0,std=1.0)

Parameter containing:
tensor([[ 0.4440, -0.0991,  0.5504, -0.5357,  0.1406],
        [ 0.7555, -0.4935, -0.5820,  1.2463, -0.1475],
        [-0.2359,  1.7288,  0.3198,  1.2990,  1.5907],
        [ 1.1822,  2.1888,  0.1475, -0.0221,  0.9578],
        [ 0.4697,  2.0269, -0.6363,  0.5704, -1.2527]], requires_grad=True)

In [10]:
nn.init.normal_(layer.weight,mean=0.0,std=0.2)

Parameter containing:
tensor([[-0.8584, -0.1769, -0.0477, -0.0912,  0.1252],
        [-0.4652, -0.0558, -0.0124,  0.1959, -0.3256],
        [-0.2992, -0.0394, -0.1621,  0.4130,  0.0724],
        [-0.2228, -0.1917,  0.0650, -0.1357,  0.0938],
        [ 0.2026,  0.3306, -0.0025, -0.1377,  0.0945]], requires_grad=True)

In [12]:
# not good idea to use constant as a weight values< but as a bias will do OK
nn.init.constant_(layer.bias,)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [15]:
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [25]:
nn.init.xavier_uniform_(layer.weight,gain=1.0)
layer.weight

Parameter containing:
tensor([[ 0.2392, -0.6794, -0.1865,  0.1975,  0.2212],
        [-0.3713, -0.5789,  0.4495, -0.3148, -0.2850],
        [ 0.1636,  0.7267, -0.2822, -0.5746, -0.3538],
        [ 0.4950,  0.2078,  0.2793,  0.5135,  0.1585],
        [ 0.2550,  0.1450, -0.1759,  0.7403, -0.0267]], requires_grad=True)

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement git (from versions: none)
ERROR: No matching distribution found for git
