In [4]:
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1.0] # единственный нейрон
weights2=[0.5,-0.93,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]

bias1=2 # Bias должен быть для каждого нейрона
bias2=3
bias3=0.5

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1, 
       inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
       inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output)
# if we want to change what our NN outputs we can only change weights and biases

[4.8, 1.17, 2.385]


In [5]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.93,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5] # Bias должен быть для каждого нейрона

some_value = -0.5
weight = 0.7
bias = 0.7

print(some_value*weight)
print(some_value+bias)

-0.35
0.19999999999999996


In [7]:
import numpy as np
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.93,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5] # Bias должен быть для каждого нейрона

out=np.dot(weights,inputs)+biases # in .dot we should pass first array with biggest dim or we get an error
print(out)

[4.8   1.17  2.385]


In [ ]:
l=[1,5,6,2] # shape=4 -- it is a 1D array,Vector
lol=[[1,5,6,2],
     [3,2,1,3]] # shape = 2,4 -- 2D Array, Matrix
lolol=[[[1,5,6,2], # shape (3,2,4) -- 3D array
     [3,2,1,3]],
    [[1,5,6,2],
     [3,2,1,3]],
    [[1,5,6,2],
     [3,2,1,3]]] 
lololol=[[[[1,5,6,2], # shape (3,3,2,4) -- 4D array or Tensor
     [3,2,1,3]],
    [[1,5,6,2],
     [3,2,1,3]],
    [[1,5,6,2],
     [3,2,1,3]]],
        [[[1,5,6,2], 
     [3,2,1,3]],
    [[1,5,6,2],
     [3,2,1,3]],
    [[1,5,6,2],
     [3,2,1,3]]] ,
        [[[1,5,6,2], 
     [3,2,1,3]],
    [[1,5,6,2],
     [3,2,1,3]],
    [[1,5,6,2],
     [3,2,1,3]]] ]

In [9]:
# batch is very usefull for calculation speed because we can run calculations in parallel
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

out=np.dot(inputs,np.array(weights).T)+biases 
print(out)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [17]:
# doing multy layer NN
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]
           
biases = [2,3,0.5]
           
weights2 = [[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]
           
biases2=[-1, 2, -0.5]

layer1_out=np.dot(inputs,np.array(weights).T)+biases 
layer2_out=np.dot(layer1_out,np.array(weights2).T)+biases2          
print(layer2_out)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [20]:
# Creating Objects
np.random.seed(0)
X= [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons)
        self.biases= np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases
        
layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)
layer1.forward(X)
# print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [21]:
pip install nnfs

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [23]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

np.random.seed(0)
X= [[1,2,3,2.5],
      [2.0,5.0,-1.0,2.0],
      [-1.5,2.7,3.3,-0.8]]
X,y=spiral_data(100,3)

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons)
        self.biases= np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases
                
        
class Activation_ReLU:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

layer1=Layer_Dense(2,5)
activation1=Activation_ReLU()
layer1.forward(X)
# print(layer1.output)

activation1.forward(layer1.output)
print(activation1.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]

In [26]:
# Softmax activation
nnfs.init()

layer_outputs=[[4.8,1.21,2.385],
               [8.9,-1.81,0.2],
               [1.41,1.051,0.026]]

exp_values=np.exp(layer_outputs)
norm_values = exp_values/np.sum(exp_values,axis=1,keepdims=True)
print(norm_values)

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [28]:

nnfs.init()

np.random.seed(0)
X= [[1,2,3,2.5],
      [2.0,5.0,-1.0,2.0],
      [-1.5,2.7,3.3,-0.8]]
X,y=spiral_data(100,3)

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.1*np.random.randn(n_inputs,n_neurons)
        self.biases= np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases
                
        
class Activation_ReLU:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)
        
class Activation_Softmax:
    def forward(self,inputs):
        exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        probabilities= exp_values / np.sum(exp_values,axis=1,keepdims=True)
        self.output=probabilities

X, y =spiral_data(samples=100,classes=3)

dense1=Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2= Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333376 0.33333224 0.333334  ]
 [0.33334652 0.33330023 0.33335322]
 [0.33333334 0.33333334 0.33333334]]
